# Generated by Django 3.0.2 on 2020-02-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OplOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webOrderId', models.CharField(max_length=20)),
                ('Offer', models.CharField(max_length=20)),
                ('initialTerm', models.IntegerField()),
                ('autoRenewalFlag', models.BooleanField()),
            ],
        ),
    ]
