# Generated by Django 3.0.2 on 2020-02-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opl', '0002_auto_20200215_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='oplorderdetails',
            name='tfEligible',
            field=models.BooleanField(default=True),
        ),
    ]
