# Generated by Django 3.0.2 on 2020-02-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opl', '0003_oplorderdetails_tfeligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplorderdetails',
            name='tfEligible',
            field=models.BooleanField(),
        ),
    ]
