# Generated by Django 3.0.2 on 2020-02-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opl', '0005_oplorderdetails_subrefid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplorderdetails',
            name='subRefId',
            field=models.CharField(default='Sub57702', max_length=20),
        ),
    ]
