# Generated by Django 2.2.11 on 2020-03-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opl', '0006_auto_20200219_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplorderdetails',
            name='subRefId',
            field=models.CharField(default='Sub99695', max_length=20),
        ),
    ]
