# Generated by Django 2.2.11 on 2020-03-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opl', '0007_auto_20200305_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='oplorderdetails',
            name='subscriptionId',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='oplorderdetails',
            name='subRefId',
            field=models.CharField(max_length=20),
        ),
    ]
